version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: imitator
      POSTGRES_PASSWORD: imitator
      POSTGRES_DB: fitness
  pgAdmin:
    image: dpage/pgadmin4
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: sysdba@domain.com
      PGADMIN_DEFAULT_PASSWORD: masterkey
